samples: samples.tsv
units: units.tsv

# the sequencing adapter
adapter: ACGGATCGATCGATCGATCGAT

ref:
  transcriptome: "data/ref/transcriptome.chr21.fa"
  species: hsapiens

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # desired false discovery rate
  FDR: 0.2
  # model for sleuth differential expression analysis
  models:
    by-condition:
      full: ~condition
      reduced: ~1

bootstrap_plots:
  color_by: condition

params:
  kallisto: "-b 100"
  cutadapt-se: ""
  cutadapt-pe: ""

plot_vars:
  # the significance level for Fdr
  sig_level: 0.1
  # the alpha for the points
  point_alpha: 0.2
